### ISSUE TITLE
Create Bot error invalid strategy list

### ISSUE THREAD

**Issue by riodda** [bogdanteodoru/py3cw#1]
Thanks for your hard work on this wrapper, very usefoul.
I'm trying to create a bot with a short script (api works as i can get the full list of my bots).
With this code
`error, data = p3cw.request(
    entity='bots',
    action='create_bot',
    payload={'name':'TEST BOT','account_id': 123456789,
             'pairs':'BAT_BTC','base_order_volume':5,
             'base_order_volume_type':'percent','take_profit':10,
             'safety_order_volume':5,'safety_order_volume_type':'percent',
             'martingale_volume_coefficient':1,'martingale_step_coefficient':5,
             'max_safety_orders':5,'stop_loss_percentage':2,
             'trailing_enabled':True,'trailing_deviation':1,'safety_order_step_percentage':2,
             'take_profit_type':'base','active_safety_orders_count':5,
             'strategy_list': [{"strategy":"manual"}] 
    }
)`

I have error `{'error': 'record_invalid', 'error_description': 'Invalid parameters', 'error_attributes': {'strategy_list': ['is invalid']}}
`

(account id if a fake number, but the real one in my test).

have tryed all the strategy list types mentioned on the 3c but i have error regardless.....
many thanks.

**Comment by bogdanteodoru** [comment]
Hi @riodda. TBH I'm not sure why you get that error. It's not coming from my wrapper. You should take it out with the guys from the 3Commas.
