### ISSUE TITLE
str has no attribute get on new smart trade v2

### ISSUE THREAD

**Issue by petekblaz** [bogdanteodoru/py3cw#12]
I keep getting this error back, when trying to create new smart_trades_v2

`{'error': True, 'msg': "Other error occurred: 'str' object has no attribute 'get'"}`

Any ideas on why this is?

Here is my code:
`error, data  = p3cw.request(
        entity='smart_trades_v2', 
        action='new', 
        payload={
            "account_id": account_id,
            "pair": pair,
            "skip_enter_step": True,
            "position": {
                "type": positionType,
                "order_type": positionOrderType,
                "units": {
                    "value": amountToBuy
                },
                "price": {
                    "value": limitOrderPrice
                },
            },
            "take_profit": {
                "enabled": takeProfitEnabled,
                "steps": [
                    {
                        "order_type": takeProfitOrderType,
                        "price": {
                            "value": takeProfitValue,
                            "type": takeProfitPriceType
                        },
                        "volume": takeProfitVolume
                    }
                ]
            },
            "stop_loss": {
                "enabled": stopLossEnabled,
                "order_type": stopLossOrderType,
                "conditional": {
                    "price": {
                        "value": stopLossPrice,
                        "type": stopLossPriceType
                    }
                }
            }
        }
    )`

**Comment by petekblaz** [comment]
It seems like only new smart trade isnt working. Anyone has any clue as to why?

**Comment by bogdanteodoru** [comment]
@petekblaz no idea why. Could you please check if you have enough balance? Another person who has the exact same error didn't have any positive balance.

**Comment by daniel100000** [comment]
I had the same issue. It actually apperas if the request was invalid, but we want to see the error message from 3commas:
`{"error":"record_invalid","error_description":"Invalid parameters","error_attributes":{"total":["must be greater than or equal to 10.0"]}}`
which I can see by inserting `print(response.text)` in request.py. 

However, your library returns 
`{'error': True, 'msg': "Other error occurred: 'str' object has no attribute 'get'"}` 
at the end and I think this should be fixed. 

By the way, thank you for work, it helped me a lot!!

**Comment by bogdanteodoru** [comment]
Better error handling will be fixed with https://github.com/bogdanteodoru/py3cw/issues/13
