### ISSUE TITLE
Error when loading Py3CW function

### ISSUE THREAD

**Issue by BoognishBear** [bogdanteodoru/py3cw#14]
The package appears to be installed and up-to-date.   However I am getting the following error when loading Py3CW. 

from py3cw.request import Py3CW

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sweetpeasimpson613/anaconda3/lib/python3.5/site-packages/py3cw/request.py", line 69
    relative_url = f"{API_VERSION_V2}{path}"

Any insight would be greatly appreciated.

**Comment by bogdanteodoru** [comment]
Hi @BoognishBear

How are you loading the library? Can you provide the full example?

**Comment by BoognishBear** [comment]
It was an user error.  Thanks for the quick response!
