### ISSUE TITLE
switch between real and paper trading

### ISSUE THREAD

**Issue by SteveL1** [bogdanteodoru/py3cw#15]
Hi,

I'm testing out a new strategy and would like to be able to ensure that the updates I make are only on the paper trading account.  Is that possible or do I need to select paper trading in the UI and then run my script?

**Comment by bogdanteodoru** [comment]
Hi @SteveL1,

You need to select the paper trade account id when you're using the script. No need to select it from the UI but rather get the paper trading account ID and use that when making queries.

**Comment by SteveL1** [comment]
Hi,

I'm afraid that didn't work.  But I managed to find that swaggerdoc and found that this call does switch between real and paper accounts:

p3cw.request(
      entity='users',
      action='change_mode', 
      payload={"mode":"paper"})

Swaggerdoc is here: 
https://github.com/3commas-io/3commas-official-api-docs/blob/master/3commas_swaggerdoc.json

Just putting it here in case someone else needs it!
