### ISSUE TITLE
"msg": "Other error occurred: record_invalid Invalid parameters."

### ISSUE THREAD

**Issue by GetSun2EZ** [bogdanteodoru/py3cw#16]
Hello guys, i have a problem.
I use the smart trade v2 and I got this error this error many times in the row but sometimes the order passes and I dont change the type of each values.

Someone can help me plz ?

**Comment by bogdanteodoru** [comment]
@GetSun2EZ can you post the code you are using? I would help a lot :)

**Comment by GetSun2EZ** [comment]
id_account = int
pair = str
unit_value = float
entry = float
levarage = str
all target = float
stop = float
I want buy a coin with a specific price. I have a other payload with a buy market but this one in most important. Thx a lot
            error, data = p3cw.request(
                entity='smart_trades_v2',
                action='new',
                payload={
                    "account_id": id_account,
                    "pair": pair,
                    "instant": "false",
                    "position": {
                        "type": "buy",
                        "units": {
                            "value": unit_value
                        },
                        "order_type": "conditional",
                        "conditional": {
                            "price": {
                                "value": entry
                            },
                            "order_type": "market"
                        }
                    },
                    "leverage": {
                        "enabled": True,
                        "type": "custom",
                        "value": leverage
                    },
                    "take_profit": {
                        "enabled": "true",
                        "steps": [
                            {
                                "order_type": "limit",
                                "price": {
                                    "value": targets[0],
                                    "type": "bid"
                                },
                                "volume": 25
                            },
                            {
                                "order_type": "limit",
                                "price": {
                                    "value": targets[1],
                                    "type": "bid"
                                },
                                "volume": 25
                            },
                            {
                                "order_type": "limit",
                                "price": {
                                    "value": targets[2],
                                    "type": "bid"
                                },
                                "volume": 25
                            },
                            {
                                "order_type": "limit",
                                "price": {
                                    "value": targets[3],
                                    "type": "bid"
                                },
                                "volume": 25
                            }
                        ]
                    },
                    "stop_loss": {
                        "enabled": "true",
                        "order_type": "market",
                        "conditional": {
                            "price": {
                                "value": stop,
                                "type": "bid"
                            }
                        }
                    }
                }
            )

**Comment by bogdanteodoru** [comment]
@GetSun2EZ if I understand correctly and the order "but sometimes the order passes" it's not something wrong from the wrapper point of view. If it was an error it would have failed every time. 

Please check if you have enough balance when trying to submit the order. Other than that if the error still persists I would recommend taking it up with the 3commas team (which is not an affiliate with me).
