### ISSUE TITLE
remove smarttrades v1

### ISSUE THREAD

**Issue by gunleik** [bogdanteodoru/py3cw#18]
I belive smart_trades (v1) doesn't work anymore. I had to use smart_trades_v2 as entity which is not mentioned in the readme. The smart_trades entity could probably be changed to match the v2 api version.
Thanks for a great wrapper :-)

**Comment by vitor-ao** [comment]
@gunleik Thank. I was almost going insane trying to figure out why it wasnt working.

**Comment by bogdanteodoru** [comment]
Hi @gunleik. Yeah, didn't have the chance to updated everything yet. Hopefully will do it in the next week or so.

**Comment by bogdanteodoru** [comment]
I've updated the README to include @vitor-ao example. Thanks.
