### ISSUE TITLE
More detailed error feedback

### ISSUE THREAD

**Issue by lathamfell** [bogdanteodoru/py3cw#19]
When a trade fails the error msg is "invalid parameters".  However, if I debug through py3cw and get the actual error feedback from 3Commas, it provides a detailed description of the parameter problems.  It would be nice if the full error msg from 3Commas were floated up and provided in the py3cw error msg.

**Comment by lathamfell** [comment]
If the Exception from __make_request() were like this, it will pass the full error msg up.  The specific part of the error msg from 3Commas is contained in 'error_attributes':

        except Exception:
            return {'error': True, 'msg': 'Other error occurred: {} {} {}.'.format(
                response_json.get('error'),
                response_json.get('error_description'),
                response_json.get('error_attributes'))}, None

**Comment by bogdanteodoru** [comment]
@lathamfell please do a pull request and I will happily merge it :)

**Comment by bogdanteodoru** [comment]
Fixed in v0.0.22
