### ISSUE TITLE
SSL Issue

### ISSUE THREAD

**Issue by meghanarora** [bogdanteodoru/py3cw#20]
Hey,

I'm trying to run the most basic connection as copied on the README on a mac and i get two errors, not sure if one is causing another. 

1) requests.exceptions.SSLError: HTTPSConnectionPool(host='api.3commas.io', port=443): Max retries exceeded with url: /public/api/ver1/deals (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1108)')))

2) UnboundLocalError: local variable 'response_json' referenced before assignment

I saw from others that the second was fixed from removing the request_options which I did as well, but it hasn't been resolved. 

I can add "verify = False" to the request to make it pass, but is this safe, or is there a better workaround?
Any insight?

**Comment by weliin** [comment]
I saw that error once when I had a lot of deals open and I hit their API too quickly.  You basically need to slow your script down a bit.  this really isn't a py3cw issue but 3commas rate limiting issue.
