### ISSUE TITLE
Forcing paper or real account mode using configurable header

### ISSUE THREAD

**Issue by fredespi** [bogdanteodoru/py3cw#23]
It would be good to be able to force the API mode using the "Forced-Mode" header. Right now I am switching between the paper and real account using the user_mode on users API but it has the negative consequence of also changing the mode in the 3commas web app which can be very confusing. Thanks.

**Comment by sgerodes** [comment]
Need this one too.

**Comment by sgerodes** [comment]
I have extended the code for this purpose. If I would be granted push permissions I will push the code.

**Comment by bogdanteodoru** [comment]
Hi @sgerodes, thanks. I've been very busy lately and didn't have time for anything unfortunately. Please do a PR and I will merge it if everything is good.

**Comment by sgerodes** [comment]
@bogdanteodoru I would like to. But I need permissions for that from you. Please add me to the project was a collaborator.

Right now I am receiving this GitHub error:

ERROR: Permission to bogdanteodoru/py3cw.git denied to sgerodes.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

**Comment by bogdanteodoru** [comment]
@sgerodes you don't need permissions to do a pull request. You can just fork my repo, do your changes there and then simply create a pull request. Check out this [link](https://opensource.com/article/19/7/create-pull-request-github)

**Comment by sgerodes** [comment]
I have implemented it in two ways. It probably needs some discussion at that place. One way is just a very restrictive additional parameter forced_mode. Has the benefit of simplicity.
https://github.com/bogdanteodoru/py3cw/pull/26

Second way is the way add any additional header to the request. The second one has the benefit of potential forward compatibility for the case other headers would be introduced to the api.
https://github.com/bogdanteodoru/py3cw/pull/27

@bogdanteodoru Its up to you to decide what is more in the style of the wrapper if any. Maximum one should be approved.

**Comment by bogdanteodoru** [comment]
Hi @sgerodes. First of all thanks for improving the library. Your help is much appreaciated it. Regarding the solution I'm keen to take the second aproach. I'm pretty sure that 3commas will be adding multiple headers/options in the future and having those forced added doesn't seem flexible to me. 

So I will merge the second solution.

**Comment by bogdanteodoru** [comment]
Custom header support deployed in v0.0.25. Will be closing this one now.

**Comment by fredespi** [comment]
thanks
