### ISSUE TITLE
Where can I get action_id and bot id and how do I create them?

### ISSUE THREAD

**Issue by Cryptoseen** [bogdanteodoru/py3cw#37]
I'm new to this and I want to use dca bot. I will also use the Freqtrade bot.  

For a strategy in freqtrade to work in partnership with 3commas dca I need to add the following to the strategy. I don't understand how to generate the action id and bot_ids, what should I write there.

`p3cw.request(
    #         entity='bots',
    #         action='start_new_deal',
    #         action_id='123123',
    #         payload={
    #             "bot_id": 123123,
    #             "pair": f"{currency}_{coin}",
    #         },`

**Comment by bogdanteodoru** [comment]
@Cryptoseen this is not a bug in the library. If you want to get familiar with the library and how things work, I recommend you go and check the 3commas library first and see how things are requested ([3commas API](https://github.com/3commas-io/3commas-official-api-docs/blob/master/bots_api.md))

This is not a replacement for that 3commas but rather a wrapper build on top of their API. You need to understand how things work before using it and the easiest place to start is their API.

Hope this helped in any way. Have a great day ahead ;)
