### ISSUE TITLE
What happens when API Limit is reached

### ISSUE THREAD

**Issue by moutikabdessabour** [bogdanteodoru/py3cw#44]
I took a look at the request.py file and I found out that the package doesn't handle `429` status code when the request is maxed out. I'd be happy to create  PR with this implemented. 

BTW great package.

PS : I already "fixed" this in my fork and added a customizable timeout for this situation.

**Comment by bogdanteodoru** [comment]
Hi @moutikabdessabour,

Yeah currently is not implemented as I initially decided that is up to the implementor to build his code around this. We could probably do some sort of "backlog" of requests when this limit is hit but then requires everything to be async. I will think about this and if time allows will implement something.

I saw what you did in your fork but would rather try to implement something on my own (just for the sake of doing it and learning).

Thanks.

**Comment by cyberjunky** [comment]
I created a PR for it... https://github.com/bogdanteodoru/py3cw/pull/45

**Comment by bogdanteodoru** [comment]
Thanks @cyberjunky, makes sense and clean.

**Comment by cyberjunky** [comment]
Thanks, hopefully you can release a new version on PyPi soon, so I can use it in my software. Thanks for your work!

**Comment by bogdanteodoru** [comment]
@cyberjunky just did it now. It's on v0.0.33.
