### ISSUE TITLE
On error the wrapper could return both {} and None

### ISSUE THREAD

**Issue by sgerodes** [bogdanteodoru/py3cw#50]
The response should be uniformly return either one or another.

**Comment by sg-rs** [comment]
@bogdanteodoru This is a good clean up. And it is already implemented. Would be great if you merge it.

**Comment by bogdanteodoru** [comment]
hey @sg-rs. Thanks for the PR. Github didn't want to mention me I had anything in progress so I must have missed it. I merged it and built v0.0.36
