### ISSUE TITLE
Historical data

### ISSUE THREAD

**Issue by shaikh1896** [bogdanteodoru/py3cw#53]
Hi Guyz,
I am using this amazing tool to connect 3commasApi using python. I need some help in getting historical data. Currently its only giving my current day data by default. How can i get say last 5-6 month data?
Thanks in advance

**Comment by sgerodes** [comment]
Hi. 
This library is calling the official API  of 3commas. If there is not endpoint for historical data in the official API, then there is none in this library. If you want historical data, you need to create a feature request in the official 3commas api repo.
https://github.com/3commas-io/3commas-official-api-docs
