### ISSUE TITLE
Will there be support for SmartTradesV2?

### ISSUE THREAD

**Issue by cwazuidema** [bogdanteodoru/py3cw#6]
There is an updated API for Smart Trades:
https://github.com/3commas-io/3commas-official-api-docs/blob/master/smart_trades_v2_api.md

Will there be support this updated API for Smart Trades?

**Comment by bogdanteodoru** [comment]
@cwazuidema Yes. I will try to update the wrapper to include this as soon as I have some spare time.

**Comment by Stef3478** [comment]
That would be appreciated, thanks!

**Comment by bogdanteodoru** [comment]
I might be late on this one as I have some work to do at my regular job. If anyone can pick this up would be much appreciated.

**Comment by am11y** [comment]
The for for Smart Trades V2 is here: https://github.com/am11y/py3cw-am11yfork

**Comment by bogdanteodoru** [comment]
@am11y, thanks. I will update the repo today I think :)

**Comment by bogdanteodoru** [comment]
I've updated the code to support SmartTrades V2. Please update to v0.0.16. Thank you all.
